import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma/prisma.service';
import { CreateTableDto } from './dto/create-table.dto';
import { UpdateTableDto } from './dto/update-table.dto';
import { OrderGateway } from '../socket/order.gateway';

@Injectable()
export class TablesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly orderGateway: OrderGateway,
  ) {
    setInterval(() => this.expireSessionsJob(), 60000);
    setInterval(() => this.autoConfirmPendingJob(), 60000);
  }

  async autoConfirmPendingJob() {
    try {
      const fiveMinsAgo = new Date(Date.now() - 5 * 60000);
      const stuckOrders = await this.prisma.order.findMany({
        where: {
          status: 'pending_confirmation',
          createdAt: { lt: fiveMinsAgo }
        }
      });
      for (const o of stuckOrders) {
        // Auto-confirm stuck orders (pending > 5 minutes without waiter action)
        await this.prisma.order.update({
          where: { id: o.id },
          data: { status: 'confirmed' }
        });
        this.orderGateway.server.emit('tableUpdated', o.tableId);
      }
    } catch (e) {
      console.error('autoConfirmPendingJob error:', e);
    }
  }

  async expireSessionsJob() {
    try {
      // Find sessions open for > 5 mins with NO orders
      const fiveMinsAgo = new Date(Date.now() - 5 * 60000);
      const expiredSessions = await this.prisma.tableSession.findMany({
        where: {
          endedAt: null,
          startedAt: { lt: fiveMinsAgo },
        },
        include: { orders: true }
      });

      for (const session of expiredSessions) {
        if (session.orders.length === 0) {
          // Expire empty sessions with no orders after 5 minutes
          await this.prisma.tableSession.update({
            where: { id: session.id },
            data: { endedAt: new Date() }
          });
          this.orderGateway.server.emit('tableUpdated', session.tableId);
        }
      }
    } catch (e) {
      console.error('expireSessionsJob error:', e);
    }
  }

  private tableCooldowns = new Map<string, number>();

  private checkCooldown(tableId: number, action: string, cooldownMs: number = 20000) {
    const key = `${tableId}-${action}`;
    const lastTime = this.tableCooldowns.get(key) || 0;
    if (Date.now() - lastTime < cooldownMs) {
      throw new BadRequestException('Please wait a moment before trying again.');
    }
    this.tableCooldowns.set(key, Date.now());
  }

  async create(dto: CreateTableDto) {
    // Auto-generate table name: find max existing number and increment
    const allTables = await this.prisma.table.findMany({
      select: { name: true }
    });
    
    let maxNum = 0;
    for (const t of allTables) {
      const match = t.name.match(/^Table\s+(\d+)$/i);
      if (match) {
        const num = parseInt(match[1], 10);
        if (num > maxNum) maxNum = num;
      }
    }
    
    const nextNum = maxNum + 1;
    const name = dto.name || `Table ${nextNum}`;
    const frontendUrl = process.env.FRONTEND_URL || 'http://localhost:5173';
    
    // Create table — qrToken is auto-generated by Prisma UUID default
    const table = await this.prisma.table.create({
      data: {
        name,
        qrCode: 'PENDING', // placeholder, updated below with token
        status: dto.status || 'empty',
      }
    });
    
    // Update QR code with token-based URL (production-safe, no raw IDs)
    const qrUrl = `${frontendUrl}/table/${table.qrToken}`;
    return this.prisma.table.update({
      where: { id: table.id },
      data: { qrCode: qrUrl }
    });
  }

  async findAll(includeDeleted: boolean = false) {
    const tables = await this.prisma.table.findMany({
      where: includeDeleted ? undefined : { isDeleted: false },
      include: {
        sessions: {
          where: { endedAt: null },
          orderBy: { startedAt: 'desc' },
          take: 1,
          include: { orders: { where: { status: { notIn: ['cancelled'] } } } }
        }
      }
    });

    return tables.map((t: any) => {
      const activeSession = t.sessions?.[0];
      const activeOrders = activeSession?.orders || [];

      const hasPending = activeOrders.some((o: any) => o.status === 'pending_confirmation');
      const hasActivePrep = activeOrders.some((o: any) => ['confirmed', 'preparing'].includes(o.status));
      const allReady = activeOrders.length > 0 && activeOrders.every((o: any) => o.status === 'ready');

      let computedState = 'occupied';
      if (!activeSession) computedState = 'available';
      else if (hasPending) computedState = 'waiting_confirm';
      else if (allReady) computedState = 'serving';
      else if (hasActivePrep) computedState = 'occupied';

      // Hide internal DB status in API response, include isLocked
      const { status, sessions, ...publishableTable } = t;
      return { 
        ...publishableTable, 
        computedState,
        isLocked: t.isLocked,
        activeSessionId: activeSession?.id || null,
        orders: activeSession?.orders || []
      };
    });
  }

  async findOne(id: number) {
    const t: any = await this.prisma.table.findUnique({ 
      where: { id }, 
      include: {
        sessions: {
          where: { endedAt: null },
          orderBy: { startedAt: 'desc' },
          take: 1,
          include: { orders: { where: { status: { notIn: ['cancelled'] } } } }
        }
      }
    });
    if (!t || t.isDeleted) throw new NotFoundException('Table not found');
    
    const activeSession = t.sessions?.[0];
    const activeOrders = activeSession?.orders || [];

    const hasPending = activeOrders.some((o: any) => o.status === 'pending_confirmation');
    const hasActivePrep = activeOrders.some((o: any) => ['confirmed', 'preparing'].includes(o.status));
    const allReady = activeOrders.length > 0 && activeOrders.every((o: any) => o.status === 'ready');

    let computedState = 'occupied';
    if (!activeSession) computedState = 'available';
    else if (hasPending) computedState = 'waiting_confirm';
    else if (allReady) computedState = 'serving';
    else if (hasActivePrep) computedState = 'occupied';
    
    const { status, sessions, ...publishableTable } = t;

    return { 
      ...publishableTable, 
      computedState,
      isLocked: t.isLocked,
      activeSessionId: activeSession?.id || null,
      orders: activeSession?.orders || []
    };
  }

  /**
   * Resolve a QR token to a table. Used by customer QR scan.
   * Returns table data without exposing internal auto-increment ID in the URL.
   */
  async findByToken(token: string) {
    const table = await this.prisma.table.findUnique({
      where: { qrToken: token },
    });
    if (!table || table.isDeleted) throw new NotFoundException('Table not found');
    return { id: table.id, name: table.name, qrToken: table.qrToken, isLocked: table.isLocked };
  }

  /**
   * Check session status for a table. Used by customer on page reload
   * to determine whether to restore state or show session-ended screen.
   */
  async getSessionStatus(tableId: number) {
    const session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null },
      orderBy: { startedAt: 'desc' },
      include: { orders: { where: { status: { notIn: ['cancelled'] } } } },
    });

    if (session) {
      return {
        active: true,
        sessionId: session.id,
        orderCount: session.orders.length,
        startedAt: session.startedAt,
      };
    }

    // Check if session recently ended
    const lastSession = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: { not: null } },
      orderBy: { endedAt: 'desc' },
    });

    return {
      active: false,
      endedAt: lastSession?.endedAt || null,
      sessionId: lastSession?.id || null,
    };
  }

  async getActiveSession(tableId: number) {
    const session = await this.prisma.tableSession.findFirst({
      where: {
        tableId,
        endedAt: null,
      },
      include: {
        orders: {
          include: {
            items: {
              include: {
                menuItem: true
              }
            }
          }
        }
      },
      orderBy: {
        startedAt: 'desc'
      }
    });



    if (!session) {
      throw new BadRequestException('NO_ACTIVE_SESSION');
    }

    return session;
  }

  async getOrCreateSessionToken(tableId: number) {
    // TABLE LOCK GUARD
    const table = await this.prisma.table.findUnique({ where: { id: tableId } });
    if (table && table.isLocked) {
      return { token: null, tableId, isLocked: true, message: 'Bàn đang bị khóa.' };
    }

    // Check for active session first
    let session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null },
      orderBy: { startedAt: 'desc' }
    });
    
    if (session) {
      return { token: session.id, tableId: session.tableId, isLocked: false };
    }

    // COOLDOWN GUARD
    const recentlyEnded = await this.prisma.tableSession.findFirst({
      where: {
        tableId,
        endedAt: { not: null, gt: new Date(Date.now() - 30000) }
      },
      orderBy: { endedAt: 'desc' }
    });

    if (recentlyEnded) {
      return { token: null, tableId, sessionEnded: true, message: 'Session recently ended' };
    }

    session = await this.prisma.tableSession.create({
      data: { tableId }
    });
    this.orderGateway.server.emit('tableUpdated', tableId);

    // Emit customer activity: new session created
    if (table) {
      this.orderGateway.emitCustomerActivity({
        tableId,
        tableName: table.name,
        type: 'SCAN_QR',
        description: `Khách đã quét QR tại ${table.name}`,
      });
    }
    
    return { token: session.id, tableId: session.tableId, isLocked: false };
  }

  async forceResetTable(tableId: number) {
    const session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null },
      include: { orders: true },
    });

    if (!session) {
      // allow safe reset
      return { success: true };
    }

    return await this.prisma.$transaction(async (tx) => {
      // Drop items (needed for constraint)
      await tx.orderItem.deleteMany({
        where: { order: { sessionId: session.id } }
      });

      await tx.order.deleteMany({
        where: { sessionId: session.id },
      });

      await tx.tableSession.update({
        where: { id: session.id },
        data: {
          endedAt: new Date(),
          totalAmount: 0,
        },
      });

      this.orderGateway.server.emit('dashboardUpdated', {});
      this.orderGateway.server.to('service').emit('tableUpdated', tableId);
      this.orderGateway.server.to('kitchen').emit('tableUpdated', tableId);
      return { success: true };
    }, { timeout: 20000 });
  }

  async getTableDebug(id: number) {
    const table = await this.prisma.table.findUnique({ where: { id } });
    const orders = await this.prisma.order.findMany({ where: { tableId: id } });
    const session = await this.prisma.tableSession.findFirst({ where: { tableId: id, endedAt: null } });
    const fullState = await this.findOne(id);
    return { table, orders, session, computedState: fullState.computedState };
  }

  async update(id: number, dto: UpdateTableDto) {
    await this.findOne(id);
    return this.prisma.table.update({ where: { id }, data: dto });
  }

  async safeDeleteTable(tableId: number) {
    const table = await this.prisma.table.findUnique({ where: { id: tableId } });
    if (!table) throw new NotFoundException('Table not found');
    if (table.isDeleted) throw new BadRequestException('Table is already deleted');

    // Close any active session (but don't destroy history)
    const activeSession = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null }
    });
    if (activeSession) {
      await this.prisma.tableSession.update({
        where: { id: activeSession.id },
        data: { endedAt: new Date() }
      });
    }

    // Soft delete — preserve all order/session history
    await this.prisma.table.update({
      where: { id: tableId },
      data: { isDeleted: true }
    });

    this.orderGateway.server.emit('dashboardUpdated', {});
    this.orderGateway.server.to('service').emit('tableUpdated', tableId);
    this.orderGateway.server.to('kitchen').emit('tableUpdated', tableId);

    return { success: true };
  }

  async restore(id: number) {
    const table = await this.prisma.table.findUnique({ where: { id } });
    if (!table) throw new NotFoundException('Table not found');

    return this.prisma.table.update({
      where: { id },
      data: { isDeleted: false },
    });
  }

  async callWaiter(id: number, user?: any) {
    this.checkCooldown(id, 'call_waiter', 30000);
    const table = await this.findOne(id);
    const message = await this.prisma.message.create({
      data: { tableId: id, sender: 'system', content: 'Khách đã gọi nhân viên' }
    });
    
    this.orderGateway.server.to(`table_${id}`).to('service').emit('newMessage', message);
    this.orderGateway.server.to('service').emit('tableNotification', { 
      tableId: id, 
      type: 'CALL_WAITER', 
      message: 'Khách đã gọi nhân viên', 
      createdAt: message.createdAt 
    });
    
    await this.prisma.auditLog.create({
      data: {
        userId: user?.id || null,
        action: 'CALL_WAITER',
        tableId: id,
        metadata: {}
      }
    });
    
    return { success: true };
  }

  async requestPayment(id: number, user?: any) {
    // Query raw table from DB — findOne() strips the 'status' field via destructuring
    const rawTable = await this.prisma.table.findUnique({ where: { id } });
    if (!rawTable) throw new NotFoundException('Table not found');
    
    if (rawTable.status === 'needs_payment') {
      throw new BadRequestException('Payment is already requested and being processed.');
    }
    this.checkCooldown(id, 'request_payment', 10000);
    
    const updatedTable = await this.prisma.table.update({
      where: { id },
      data: { status: 'needs_payment' }
    });
    
    const message = await this.prisma.message.create({
      data: { tableId: id, sender: 'system', content: 'Khách yêu cầu thanh toán' }
    });
    
    this.orderGateway.server.to(`table_${id}`).to('service').emit('newMessage', message);
    this.orderGateway.server.to('service').emit('tableNotification', { 
      tableId: id, 
      type: 'REQUEST_PAYMENT', 
      message: 'Khách yêu cầu thanh toán', 
      createdAt: message.createdAt 
    });
    this.orderGateway.server.emit('dashboardUpdated', {});
    this.orderGateway.server.to('service').emit('tableUpdated', id);
    
    await this.prisma.auditLog.create({
      data: {
        userId: user?.id || null,
        action: 'REQUEST_PAYMENT',
        tableId: id,
        metadata: {}
      }
    });
    
    return updatedTable;
  }

  async getActiveOrders(id: number) {
    return this.prisma.order.findMany({
      where: {
        tableId: id,
        status: { notIn: ['cancelled'] },
        session: {
            endedAt: null
        }
      },
      include: { items: { include: { menuItem: true } } },
      orderBy: { createdAt: 'desc' }
    });
  }

  async fixStuckTable(tableId: number) {
    const session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null },
      include: { orders: true }
    });

    if (!session) return;

    const hasPending = session.orders.some((o: any) => o.status === 'pending_confirmation');

    if (hasPending) {
      // Force-confirm stuck pending orders before bill preview

      await this.prisma.order.updateMany({
        where: { sessionId: session.id },
        data: { status: 'confirmed' }
      });
    }
  }

  async getPreviewBill(tableId: number) {
    const session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null },
      orderBy: { startedAt: 'desc' },
      include: {
        table: true,
        orders: {
          where: { status: { not: 'cancelled' } },
          include: {
            items: { include: { menuItem: true } }
          }
        }
      }
    });

    if (!session) {
      throw new BadRequestException('NO_ACTIVE_SESSION');
    }

    // Flatten all order items, EXCLUDE cancelled items, aggregate by menuItemId+note
    const itemMap = new Map<string, { name: string; price: number; quantity: number; note: string }>();

    for (const order of session.orders) {
      for (const item of order.items) {
        // ONLY ready items should appear on the bill
        if (item.status !== 'ready') continue;

        const price = Number(item.price || 0);
        const key = `${item.menuItemId}-${item.note || ''}`;

        if (itemMap.has(key)) {
          const existing = itemMap.get(key)!;
          existing.quantity += item.quantity;
        } else {
          itemMap.set(key, {
            name: item.name || item.menuItem?.name || 'Item',
            price,
            quantity: item.quantity,
            note: item.note || '',
          });
        }
      }
    }

    const items = Array.from(itemMap.values());
    const subtotal = items.reduce((sum, i) => sum + i.price * i.quantity, 0);

    await this.fixStuckTable(tableId);

    return {
      tableId,
      tableNumber: session.table?.name?.replace('Table', '').trim() || String(tableId),
      sessionId: session.id,
      startedAt: session.startedAt,
      items,
      subtotal,
      total: subtotal,
      orderCount: session.orders.length,
    };
  }

  async printPreviewBill(tableId: number) {
    // PREVIEW BILL SAFE MODE: ONLY READ DATA
    const session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null }
    });
    if (!session) return { success: true };

    return { success: true };
  }

  async checkout(tableId: number, user?: any) {
    if (!tableId) {
      throw new BadRequestException('Invalid tableId');
    }

    const transactionResult = await this.prisma.$transaction(async (tx) => {
      const session = await tx.tableSession.findFirst({
        where: { tableId, endedAt: null },
        orderBy: { startedAt: 'desc' },
        include: {
          table: true,
          orders: {
            where: { status: { not: 'cancelled' } },
            include: {
              items: { include: { menuItem: true } }
            }
          }
        }
      });

      if (!session) {
        throw new BadRequestException('NO_ACTIVE_SESSION');
      }

      if (session.orders.length === 0) {
        throw new BadRequestException('Bàn chưa có order');
      }

      // Build aggregated item list of only ready items, excluding cancelled items/orders
      const itemMap = new Map<string, { name: string; price: number; quantity: number; note: string }>();

      for (const order of session.orders) {
        for (const item of order.items) {
          if (item.status === 'ready') {
            const price = Number(item.price || 0);
            const key = `${item.menuItemId}-${item.note || ''}`;

            if (itemMap.has(key)) {
              itemMap.get(key)!.quantity += item.quantity;
            } else {
              itemMap.set(key, {
                name: item.name || item.menuItem?.name || 'Món ăn',
                price,
                quantity: item.quantity,
                note: item.note || '',
              });
            }
          }
        }
      }

      const items = Array.from(itemMap.values());
      const totalAmount = items.reduce((sum, i) => sum + i.price * i.quantity, 0);

      if (totalAmount === 0) {
        throw new BadRequestException('Chưa có món nào hoàn tất để thanh toán');
      }

      const paidAt = new Date();
      const billSnapshot = {
        tableId: session.tableId,
        tableNumber: session.table?.name?.replace('Table', '').trim() || String(session.tableId),
        tableName: session.table?.name || `Bàn ${session.tableId}`,
        sessionId: session.id,
        startedAt: session.startedAt,
        paidAt,
        items,
        subtotal: totalAmount,
        total: totalAmount,
      };

      // Close session
      await tx.tableSession.update({
        where: { id: session.id },
        data: {
          endedAt: paidAt,
          paidAt,
          totalAmount,
          billSnapshot: billSnapshot as any,
        }
      });

      // Reset Table
      await tx.table.update({
        where: { id: tableId },
        data: { status: 'empty' }
      });

      await tx.message.deleteMany({
        where: { tableId }
      });

      await tx.auditLog.create({
        data: {
          userId: user?.id || null,
          action: 'CHECKOUT',
          tableId: tableId,
          metadata: { totalAmount, sessionId: session.id }
        }
      });

      return { totalAmount, sessionId: session.id };
    }, { timeout: 20000 });

    // Use centralized gateway emission
    this.orderGateway.emitPaymentCompleted({ tableId, sessionId: transactionResult.sessionId });
    return { success: true, totalAmount: transactionResult.totalAmount, sessionId: transactionResult.sessionId };
  }

  /**
   * Create a QR payment for a table's active session.
   * Delegates to PaymentsService-compatible logic.
   */
  async createPaymentForTable(tableId: number) {
    const session = await this.prisma.tableSession.findFirst({
      where: { tableId, endedAt: null },
      orderBy: { startedAt: 'desc' },
      include: {
        table: true,
        orders: {
          where: { status: { notIn: ['cancelled'] } },
          include: { items: true }
        }
      }
    });

    if (!session) {
      throw new BadRequestException('NO_ACTIVE_SESSION');
    }

    if (session.orders.length === 0) {
      throw new BadRequestException('Bàn chưa có order');
    }

    // Calculate total of only ready items
    let subtotal = 0;
    for (const order of session.orders) {
      for (const item of order.items) {
        if (item.status === 'ready') {
          subtotal += Number(item.price || 0) * item.quantity;
        }
      }
    }

    if (subtotal === 0) {
      throw new BadRequestException('Chưa có món nào hoàn tất để thanh toán');
    }

    // Check if there's already a pending payment for this session
    const existingPayment = await this.prisma.payment.findFirst({
      where: {
        order: { sessionId: session.id },
        status: 'pending',
      }
    });

    if (existingPayment) {
      if (Number(existingPayment.amount) !== subtotal) {
        await this.prisma.payment.update({
          where: { id: existingPayment.id },
          data: { amount: subtotal }
        });
      }
      return {
        paymentId: existingPayment.id,
        amount: subtotal,
        tableId,
        sessionId: session.id,
      };
    }

    const firstOrder = session.orders[0];
    const payment = await this.prisma.payment.create({
      data: {
        order: { connect: { id: firstOrder.id } },
        method: 'bank',
        amount: subtotal,
        status: 'pending',
      }
    });

    // Update table status
    await this.prisma.table.update({
      where: { id: tableId },
      data: { status: 'needs_payment' }
    });

    this.orderGateway.server.to('service').emit('tableUpdated', tableId);

    return {
      paymentId: payment.id,
      amount: subtotal,
      tableId,
      sessionId: session.id,
    };
  }

  // ==========================================
  // TABLE LOCK SYSTEM (Feature #3)
  // ==========================================

  async lockTable(tableId: number, user?: any) {
    const table = await this.prisma.table.findUnique({ where: { id: tableId } });
    if (!table) throw new NotFoundException('Table not found');
    if (table.isLocked) {
      throw new BadRequestException('Bàn đã bị khóa rồi.');
    }

    await this.prisma.table.update({
      where: { id: tableId },
      data: { isLocked: true }
    });

    this.orderGateway.emitTableLocked({
      tableId,
      isLocked: true,
      tableName: table.name,
    });

    await this.prisma.auditLog.create({
      data: {
        userId: user?.id || null,
        action: 'LOCK_TABLE',
        tableId,
        metadata: {}
      }
    });

    return { success: true, isLocked: true };
  }

  async unlockTable(tableId: number, user?: any) {
    const table = await this.prisma.table.findUnique({ where: { id: tableId } });
    if (!table) throw new NotFoundException('Table not found');
    if (!table.isLocked) {
      throw new BadRequestException('Bàn không bị khóa.');
    }

    await this.prisma.table.update({
      where: { id: tableId },
      data: { isLocked: false }
    });

    this.orderGateway.emitTableLocked({
      tableId,
      isLocked: false,
      tableName: table.name,
    });

    await this.prisma.auditLog.create({
      data: {
        userId: user?.id || null,
        action: 'UNLOCK_TABLE',
        tableId,
        metadata: {}
      }
    });

    return { success: true, isLocked: false };
  }

  async getBillSnapshot(sessionId: string) {
    const session = await this.prisma.tableSession.findUnique({
      where: { id: sessionId }
    });
    if (!session) {
      throw new NotFoundException('Session not found');
    }
    return session.billSnapshot || null;
  }
}